### PR TITLE
Fixed URLs and added Brandon as author

### PR DESCRIPTION
**Pull request by drallgood**
Removed the references to my old repo (which no longer exists)

### CODE REVIEW

**Comment by imathis** [comment]
Thanks :)

**Comment by drallgood** [comment]
Glad I could help :)

There's one more pull request I'm working on right now...

**Comment by imathis** [comment]
You may want to hold off for a bit. I'm rebuilding Octopress Ink to support multilingual category indexes by default. This means that any plugin that ships with a category-index.html or category-feed.xml will automatically get it replicated for each category, with built in support for multiple languages. This means that this plugin will lose most of its code, and it also means that any Theme can ship with a category index page that matches its particular HTML with great ease.

**Comment by drallgood** [comment]
Oh nice!

I'm already done, though. Only minor fixes :) You can close them if they aren't relevant anymore...

**Pull request merged**
