### PR TITLE
Simplified Ink plugin

### PR DESCRIPTION
**Pull request by imathis**
Thanks a bunch for kicking this plugin off @drallgood! I thought you might like to see the changes I've made, so I added this PR.

As a summary, I:
- Added support for multilingual configuration
- Replaced page asset with something simpler

There's still a lot to be done, but it's shaping up nicely. Thanks!

### CODE REVIEW

**Comment by imathis** [comment]
Using includes as a template was a clever move, but I think I should probably add a template asset which works similarly but doesn't confuse things by being listed as an include.

**Comment by drallgood** [comment]
Thanks @imathis 
I like those simplifications a lot. Not using an Asset and simply creating a Jekyll page was a much better move.

As for the templates:
I agree. I alternated between using layouts and includes while developing this. Neither one really fits.

Do you want to take ownership of the `octopress-categories` gem? Otherwise I'd just delete it now that you've moved the plugin to the main Octopress org :smile:

**Comment by imathis** [comment]
My ideal is that templates can be used from other plugins. So this could use it's own, but if there is a theme, it will try to use a category template in the theme. This way the HTML will be as consistent as possible and people won't need to override things and theme makers won't have to include instructions on how to make this use html that is compatible with the theme.

> Do you want to take ownership of the octopress-categories gem?

I'll probably just continue working on this gem here. Thanks for getting this going! I wasn't originally going to use an Octopress Ink plugin, but having seen what you've done, I think it's a good move.

**Comment by drallgood** [comment]
I was talking about the gem on rubygems ;) 
It was always my intention to move things to the official octopress org, hence the name of the plugin and the way I've set things up. 

Glad I could help :smile:

**Comment by imathis** [comment]
@drallgood Ah, I understand. I'm trying to figure out what I want to call this. I'm leaning toward octopress-category-index but the way this plugin is shaping up, it's quite easy to use this to create tag indexes as well as category indexes. The name octopress-categories is a bit less descriptive so I don't know that I'll end up using it for this. If you want to transfer the ownership to me then at least I could use it for something else if I decide to at some point.

**Comment by drallgood** [comment]
@imathis 
Yeah. Initially I was planning on adding category feeds to this, but now I'm thinking that might not be the best idea. In that case the name octopress-categories would've made a little bit more sense....

I've transferred ownership, as promised :smile:

**Comment by imathis** [comment]
Thanks!

**Pull request merged**
